version: '3.8'

services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastcartradeDB
    volumes:
      - db_datos:/var/lib/mysql
    networks:
      red_backend:
        ipv4_address: 192.168.1.3

  backend:
    image: node:18
    container_name: backend
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./servidor:/app
    command: >
      bash -c "
        apt update && 
        apt install -y curl &&
        curl -o /usr/local/bin/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
        chmod +x /usr/local/bin/wait-for-it.sh &&
        /usr/local/bin/wait-for-it.sh 192.168.1.3:3306 --timeout=30 -- node app.js
      "
    ports:
      - "3000:3000"
    networks:
      red_backend:
        ipv4_address: 192.168.1.2
      red_frontend:
        ipv4_address: 192.168.2.2

  frontend:
    image: david839/angular
    container_name: frontend
    depends_on:
      - backend
    working_dir: /app
    volumes:
      - ./cliente:/app
    command: >
      bash -c "
        npm install &&
        ng serve --host 0.0.0.0
      "
    ports:
      - "4200:4200"
    networks:
      red_frontend:
        ipv4_address: 192.168.2.3

volumes:
  db_datos:

networks:
  red_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  red_frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24


# ğŸ”§ RED red_backend (192.168.1.0/24)
# Servicio	      IP	              Puerto interno	Puerto externo
# db	        192.168.1.3	                3306	 
# backend	    192.168.1.2	                3000	        3000	


# ğŸŒ RED red_frontend (192.168.2.0/24)
# Servicio	      IP	             Puerto interno	Puerto externo	
# backend	    192.168.2.2	              3000	      3000	
# frontend	  192.168.2.3	              4200	      4200
